version: "3.9"

services:
  client:
    build: ./client
    restart: on-failure
    ports:
      - target: 5173
        published: 5173
    depends_on:
      - server
  server:
    build: ./server
    restart: on-failure
    ports:
      - target: 5000
        published: 5000
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: eshop
      DB_USER: eshoprole
      DB_PASSWORD: 12345
      AUTH_SECRET_KEY: supersecretkey
    depends_on:
      - database
  database:
    image: "postgres:15.3"
    restart: on-failure
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: eshoprole
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: eshop
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


networks:
  default:
    name: eshop_network
